### ISSUE TITLE
Correct baseline_estimators docstring

### ISSUE THREAD

**Issue by agh208** [TomMonks/forecast-tools#42]
Hope it's alright for me to add this an issue here, apologies if not. It is just something I spotted whilst looking into the functions.

Docstring for baseline_estimators function currently contains:
average_lookback - int,
        number of lagged periods that average baseline includes
(currently on lines 995-996)
But this is not a possible input for the function (currently only seasonal_period)

**Comment by TomMonks** [comment]
Sorry - this feature was deprecated and then removed, but the documentation wasn't updated.  Will issue a fix in the next patch

**Comment by TomMonks** [comment]
This patched in dev and will be released in v0.1.7

**Comment by TomMonks** [comment]
patch/deployed v.0.1.7
